import { Country } from "./country" 

export const countries: Country[] =[
    {code :"BD" ,countryName: "Bangladesh"},
    {code :"BE" ,countryName: "Belgium"},
    {code :"BF" ,countryName: "Burkina Faso"},
    {code :"BG" ,countryName: "Bulgaria"},
    {code :"BA" ,countryName: "Bosnia and Herzegovina"},
    {code :"BB" ,countryName: "Barbados"},
    {code :"WF" ,countryName: "Wallis and Futuna"},
    {code :"BL" ,countryName: "Saint Barthelemy"},
    {code :"BM" ,countryName: "Bermuda"},
    {code :"BN" ,countryName: "Brunei"},
    {code :"BO" ,countryName: "Bolivia"},
    {code :"BH" ,countryName: "Bahrain"},
    {code :"BI" ,countryName: "Burundi"},
    {code :"BJ" ,countryName: "Benin"},
    {code :"BT" ,countryName: "Bhutan"},
    {code :"JM" ,countryName: "Jamaica"},
    {code :"BV" ,countryName: "Bouvet Island"},
    {code :"BW" ,countryName: "Botswana"},
    {code :"WS" ,countryName: "Samoa"},
    {code :"BQ" ,countryName: "Bonaire, Saint Eustatius and Saba "},
    {code :"BR" ,countryName: "Brazil"},
    {code :"BS" ,countryName: "Bahamas"},
    {code :"JE" ,countryName: "Jersey"},
    {code :"BY" ,countryName: "Belarus"},
    {code :"BZ" ,countryName: "Belize"},
    {code :"RU" ,countryName: "Russia"},
    {code :"RW" ,countryName: "Rwanda"},
    {code :"RS" ,countryName: "Serbia"},
    {code :"TL" ,countryName: "East Timor"},
    {code :"RE" ,countryName: "Reunion"},
    {code :"TM" ,countryName: "Turkmenistan"},
    {code :"TJ" ,countryName: "Tajikistan"},
    {code :"RO" ,countryName: "Romania"},
    {code :"TK" ,countryName: "Tokelau"},
    {code :"GW" ,countryName: "Guinea-Bissau"},
    {code :"GU" ,countryName: "Guam"},
    {code :"GT" ,countryName: "Guatemala"},
    {code :"GS" ,countryName: "South Georgia and the South Sandwich Islands"},
    {code :"GR" ,countryName: "Greece"},
    {code :"GQ" ,countryName: "Equatorial Guinea"},
    {code :"GP" ,countryName: "Guadeloupe"},
    {code :"JP" ,countryName: "Japan"},
    {code :"GY" ,countryName: "Guyana"},
    {code :"GG" ,countryName: "Guernsey"},
    {code :"GF" ,countryName: "French Guiana"},
    {code :"GE" ,countryName: "Georgia"},
    {code :"GD" ,countryName: "Grenada"},
    {code :"GB" ,countryName: "United Kingdom"},
    {code :"GA" ,countryName: "Gabon"},
    {code :"SV" ,countryName: "El Salvador"},
    {code :"GN" ,countryName: "Guinea"},
    {code :"GM" ,countryName: "Gambia"},
    {code :"GL" ,countryName: "Greenland"},
    {code :"GI" ,countryName: "Gibraltar"},
    {code :"GH" ,countryName: "Ghana"},
    {code :"OM" ,countryName: "Oman"},
    {code :"TN" ,countryName: "Tunisia"},
    {code :"JO" ,countryName: "Jordan"},
    {code :"HR" ,countryName: "Croatia"},
    {code :"HT" ,countryName: "Haiti"},
    {code :"HU" ,countryName: "Hungary"},
    {code :"HK" ,countryName: "Hong Kong"},
    {code :"HN" ,countryName: "Honduras"},
    {code :"HM" ,countryName: "Heard Island and McDonald Islands"},
    {code :"VE" ,countryName: "Venezuela"},
    {code :"PR" ,countryName: "Puerto Rico"},
    {code :"PS" ,countryName: "Palestinian Territory"},
    {code :"PW" ,countryName: "Palau"},
    {code :"PT" ,countryName: "Portugal"},
    {code :"SJ" ,countryName: "Svalbard and Jan Mayen"},
    {code :"PY" ,countryName: "Paraguay"},
    {code :"IQ" ,countryName: "Iraq"},
    {code :"PA" ,countryName: "Panama"},
    {code :"PF" ,countryName: "French Polynesia"},
    {code :"PG" ,countryName: "Papua New Guinea"},
    {code :"PE" ,countryName: "Peru"},
    {code :"PK" ,countryName: "Pakistan"},
    {code :"PH" ,countryName: "Philippines"},
    {code :"PN" ,countryName: "Pitcairn"},
    {code :"PL" ,countryName: "Poland"},
    {code :"PM" ,countryName: "Saint Pierre and Miquelon"},
    {code :"ZM" ,countryName: "Zambia"},
    {code :"EH" ,countryName: "Western Sahara"},
    {code :"EE" ,countryName: "Estonia"},
    {code :"EG" ,countryName: "Egypt"},
    {code :"ZA" ,countryName: "South Africa"},
    {code :"EC" ,countryName: "Ecuador"},
    {code :"IT" ,countryName: "Italy"},
    {code :"VN" ,countryName: "Vietnam"},
    {code :"SB" ,countryName: "Solomon Islands"},
    {code :"ET" ,countryName: "Ethiopia"},
    {code :"SO" ,countryName: "Somalia"},
    {code :"ZW" ,countryName: "Zimbabwe"},
    {code :"SA" ,countryName: "Saudi Arabia"},
    {code :"ES" ,countryName: "Spain"},
    {code :"ER" ,countryName: "Eritrea"},
    {code :"ME" ,countryName: "Montenegro"},
    {code :"MD" ,countryName: "Moldova"},
    {code :"MG" ,countryName: "Madagascar"},
    {code :"MF" ,countryName: "Saint Martin"},
    {code :"MA" ,countryName: "Morocco"},
    {code :"MC" ,countryName: "Monaco"},
    {code :"UZ" ,countryName: "Uzbekistan"},
    {code :"MM" ,countryName: "Myanmar"},
    {code :"ML" ,countryName: "Mali"},
    {code :"MO" ,countryName: "Macao"},
    {code :"MN" ,countryName: "Mongolia"},
    {code :"MH" ,countryName: "Marshall Islands"},
    {code :"MK" ,countryName: "Macedonia"},
    {code :"MU" ,countryName: "Mauritius"},
    {code :"MT" ,countryName: "Malta"},
    {code :"MW" ,countryName: "Malawi"},
    {code :"MV" ,countryName: "Maldives"},
    {code :"MQ" ,countryName: "Martinique"},
    {code :"MP" ,countryName: "Northern Mariana Islands"},
    {code :"MS" ,countryName: "Montserrat"},
    {code :"MR" ,countryName: "Mauritania"},
    {code :"IM" ,countryName: "Isle of Man"},
    {code :"UG" ,countryName: "Uganda"},
    {code :"TZ" ,countryName: "Tanzania"},
    {code :"MY" ,countryName: "Malaysia"},
    {code :"MX" ,countryName: "Mexico"},
    {code :"IL" ,countryName: "Israel"},
    {code :"FR" ,countryName: "France"},
    {code :"IO" ,countryName: "British Indian Ocean Territory"},
    {code :"SH" ,countryName: "Saint Helena"},
    {code :"FI" ,countryName: "Finland"},
    {code :"FJ" ,countryName: "Fiji"},
    {code :"FK" ,countryName: "Falkland Islands"},
    {code :"FM" ,countryName: "Micronesia"},
    {code :"FO" ,countryName: "Faroe Islands"},
    {code :"NI" ,countryName: "Nicaragua"},
    {code :"NL" ,countryName: "Netherlands"},
    {code :"NO" ,countryName: "Norway"},
    {code :"NA" ,countryName: "Namibia"},
    {code :"VU" ,countryName: "Vanuatu"},
    {code :"NC" ,countryName: "New Caledonia"},
    {code :"NE" ,countryName: "Niger"},
    {code :"NF" ,countryName: "Norfolk Island"},
    {code :"NG" ,countryName: "Nigeria"},
    {code :"NZ" ,countryName: "New Zealand"},
    {code :"NP" ,countryName: "Nepal"},
    {code :"NR" ,countryName: "Nauru"},
    {code :"NU" ,countryName: "Niue"},
    {code :"CK" ,countryName: "Cook Islands"},
    {code :"XK" ,countryName: "Kosovo"},
    {code :"CI" ,countryName: "Ivory Coast"},
    {code :"CH" ,countryName: "Switzerland"},
    {code :"CO" ,countryName: "Colombia"},
    {code :"CN" ,countryName: "China"},
    {code :"CM" ,countryName: "Cameroon"},
    {code :"CL" ,countryName: "Chile"},
    {code :"CC" ,countryName: "Cocos Islands"},
    {code :"CA" ,countryName: "Canada"},
    {code :"CG" ,countryName: "Republic of the Congo"},
    {code :"CF" ,countryName: "Central African Republic"},
    {code :"CD" ,countryName: "Democratic Republic of the Congo"},
    {code :"CZ" ,countryName: "Czech Republic"},
    {code :"CY" ,countryName: "Cyprus"},
    {code :"CX" ,countryName: "Christmas Island"},
    {code :"CR" ,countryName: "Costa Rica"},
    {code :"CW" ,countryName: "Curacao"},
    {code :"CV" ,countryName: "Cape Verde"},
    {code :"CU" ,countryName: "Cuba"},
    {code :"SZ" ,countryName: "Swaziland"},
    {code :"SY" ,countryName: "Syria"},
    {code :"SX" ,countryName: "Sint Maarten"},
    {code :"KG" ,countryName: "Kyrgyzstan"},
    {code :"KE" ,countryName: "Kenya"},
    {code :"SS" ,countryName: "South Sudan"},
    {code :"SR" ,countryName: "Suriname"},
    {code :"KI" ,countryName: "Kiribati"},
    {code :"KH" ,countryName: "Cambodia"},
    {code :"KN" ,countryName: "Saint Kitts and Nevis"},
    {code :"KM" ,countryName: "Comoros"},
    {code :"ST" ,countryName: "Sao Tome and Principe"},
    {code :"SK" ,countryName: "Slovakia"},
    {code :"KR" ,countryName: "South Korea"},
    {code :"SI" ,countryName: "Slovenia"},
    {code :"KP" ,countryName: "North Korea"},
    {code :"KW" ,countryName: "Kuwait"},
    {code :"SN" ,countryName: "Senegal"},
    {code :"SM" ,countryName: "San Marino"},
    {code :"SL" ,countryName: "Sierra Leone"},
    {code :"SC" ,countryName: "Seychelles"},
    {code :"KZ" ,countryName: "Kazakhstan"},
    {code :"KY" ,countryName: "Cayman Islands"},
    {code :"SG" ,countryName: "Singapore"},
    {code :"SE" ,countryName: "Sweden"},
    {code :"SD" ,countryName: "Sudan"},
    {code :"DO" ,countryName: "Dominican Republic"},
    {code :"DM" ,countryName: "Dominica"},
    {code :"DJ" ,countryName: "Djibouti"},
    {code :"DK" ,countryName: "Denmark"},
    {code :"VG" ,countryName: "British Virgin Islands"},
    {code :"DE" ,countryName: "Germany"},
    {code :"YE" ,countryName: "Yemen"},
    {code :"DZ" ,countryName: "Algeria"},
    {code :"US" ,countryName: "United States"},
    {code :"UY" ,countryName: "Uruguay"},
    {code :"YT" ,countryName: "Mayotte"},
    {code :"UM" ,countryName: "United States Minor Outlying Islands"},
    {code :"LB" ,countryName: "Lebanon"},
    {code :"LC" ,countryName: "Saint Lucia"},
    {code :"LA" ,countryName: "Laos"},
    {code :"TV" ,countryName: "Tuvalu"},
    {code :"TW" ,countryName: "Taiwan"},
    {code :"TT" ,countryName: "Trinidad and Tobago"},
    {code :"TR" ,countryName: "Turkey"},
    {code :"LK" ,countryName: "Sri Lanka"},
    {code :"LI" ,countryName: "Liechtenstein"},
    {code :"LV" ,countryName: "Latvia"},
    {code :"TO" ,countryName: "Tonga"},
    {code :"LT" ,countryName: "Lithuania"},
    {code :"LU" ,countryName: "Luxembourg"},
    {code :"LR" ,countryName: "Liberia"},
    {code :"LS" ,countryName: "Lesotho"},
    {code :"TH" ,countryName: "Thailand"},
    {code :"TF" ,countryName: "French Southern Territories"},
    {code :"TG" ,countryName: "Togo"},
    {code :"TD" ,countryName: "Chad"},
    {code :"TC" ,countryName: "Turks and Caicos Islands"},
    {code :"LY" ,countryName: "Libya"},
    {code :"VA" ,countryName: "Vatican"},
    {code :"VC" ,countryName: "Saint Vincent and the Grenadines"},
    {code :"AE" ,countryName: "United Arab Emirates"},
    {code :"AD" ,countryName: "Andorra"},
    {code :"AG" ,countryName: "Antigua and Barbuda"},
    {code :"AF" ,countryName: "Afghanistan"},
    {code :"AI" ,countryName: "Anguilla"},
    {code :"VI" ,countryName: "U.S. Virgin Islands"},
    {code :"IS" ,countryName: "Iceland"},
    {code :"IR" ,countryName: "Iran"},
    {code :"AM" ,countryName: "Armenia"},
    {code :"AL" ,countryName: "Albania"},
    {code :"AO" ,countryName: "Angola"},
    {code :"AQ" ,countryName: "Antarctica"},
    {code :"AS" ,countryName: "American Samoa"},
    {code :"AR" ,countryName: "Argentina"},
    {code :"AU" ,countryName: "Australia"},
    {code :"AT" ,countryName: "Austria"},
    {code :"AW" ,countryName: "Aruba"},
    {code :"IN" ,countryName: "India"},
    {code :"AX" ,countryName: "Aland Islands"},
    {code :"AZ" ,countryName: "Azerbaijan"},
    {code :"IE" ,countryName: "Ireland"},
    {code :"ID" ,countryName: "Indonesia"},
    {code :"UA" ,countryName: "Ukraine"},
    {code :"QA" ,countryName: "Qatar"},
    {code :"MZ" ,countryName: "Mozambique"}
]